class AppIcons {
  AppIcons._();

  static const String logo = "assets/svg/logo.svg";
  static const String dashboard = "assets/svg/dashboard.svg";
  static const String resume = "assets/svg/resume.svg";
  static const String home = "assets/svg/home.svg";
  static const String file = "assets/svg/file.svg";
  static const String gallery = "assets/svg/gallery.svg";
  static const String code = "assets/svg/code.svg";
  static const String hand = "assets/svg/hand.svg";
  static const String instagram = "assets/svg/instagram.svg";
  static const String github = "assets/svg/github.svg";
  static const String linkedin = "assets/svg/linkedin.svg";
  static const String send = "assets/svg/send.svg";
  static const String mouse = "assets/svg/mouse.svg";
  static const String tinyCode = "assets/svg/tiny_code.svg";
  static const String arrowRight = "assets/svg/arrow_right.svg";
  static const String rocket = "assets/svg/rocket.svg";
  static const String puzzle = "assets/svg/puzzle.svg";
  static const String gear = "assets/svg/gear.svg";
  static const String close = "assets/svg/close.svg";
  static const String check = "assets/svg/check.svg";
  static const String flutter = "assets/svg/flutter.svg";
  static const String dart = "assets/svg/dart.svg";
  static const String firebase = "assets/svg/firebase.svg";
  static const String android = "assets/svg/android.svg";
  static const String expressJS = "assets/svg/express_js.svg";
  static const String javascript = "assets/svg/javascript.svg";
  static const String figma = "assets/svg/figma.svg";
  static const String kotlin = "assets/svg/kotlin.svg";
  static const String sendEmail = "assets/svg/send_email.svg";
  static const String whatsapp = "assets/svg/whatsapp.svg";
  static const String sipuma = "assets/svg/sipuma.svg";
  static const String scooter = "assets/svg/scooter.svg";
  static const String phone = "assets/svg/phone.svg";
  static const String download = "assets/svg/download.svg";
  static const String platform = "assets/svg/platform.svg";
  static const String playstore = "assets/svg/playstore.svg";
  static const String appstore = "assets/svg/appstore.svg";
}
